name: Windows
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        qt_ver: [5.12.12]
        qt_target: [desktop]
        qt_arch: [win32_msvc2017]
        include:
          - qt_arch: win32_msvc2017
            msvc_arch: x86
    env:
      targetName: OmniEdge-windows.exe
      INNO_VERSION: 6.2.0
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_ver }}
          target: ${{ matrix.qt_target }}
          arch: ${{ matrix.qt_arch }}
               
      - name: Download Inno Setup installer
        run: curl -L -o installer.exe http://files.jrsoftware.org/is/6/innosetup-${{ env.INNO_VERSION }}.exe

      - name: Install Inno Setup
        run: |
          ./installer.exe /verysilent /allusers /dir=inst
          dir "C:\Program Files (x86)"
        
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - name: msvc-build
        id: build
        shell: cmd
        env:
          vc_arch: ${{ matrix.msvc_arch }}
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" %vc_arch%
          D:\a\omniedge-windows\Qt\5.12.12\msvc2017\bin\qmake.exe OmniEdge.pro
          dir
          dir ".\build-package\build\"
      
      - name: package
        # if: startsWith(github.event.ref, 'refs/tags/')
        id: package      
        env:
          archiveName: ${{ matrix.qt_ver }}-${{ matrix.qt_target }}-${{ matrix.qt_arch }}
          msvcArch: ${{ matrix.msvc_arch }}          
        shell: cmd
        run: |
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" /q .\build-package\omniedge_withTAP_V02_bat.iss
        
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.package.outputs.packageName }}
          path: ${{ steps.package.outputs.packageName }}
      # tag 上传Release
      - name: uploadRelease
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.package.outputs.packageName }}.zip
          asset_name: ${{ steps.package.outputs.packageName }}.zip
          tag: ${{ github.ref }}
          overwrite: true 
